# Generated by Django 5.1.4 on 2024-12-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='stroyline',
            new_name='storyline',
        ),
    ]
